### ISSUE TITLE
Hold Menu w/ Expo 49

### ISSUE THREAD

**Issue by flemingvincent** [arasors/expo-sdk49-with-router#1]
I see that you've added react-native-hold-menu to the project, however, I do not see it used anywhere. I am looking to use this library with Expo 49, but I have not been able to get it working correctly. Can you show it being used in the project?

**Comment by arasors** [comment]
Since "context menu" elements are native elements, you should switch to bare workflow with "npx expo prebuild". Then "yarn add expo-dev-client". Now you are ready.

**Comment by flemingvincent** [comment]
@arasors Have you verified that it works in the dev client?

**Comment by arasors** [comment]
Imm, no. Actually he might be wrong but I have used expo action sheet before. I think hold menu will work too.
